### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by Rbrq03** [ldynx/harmony-zero-t2i#1]
Hello @ldynx, congratulations for your great job!
Do you have a plan/timeline for code release?

**Comment by ldynx** [comment]
Dear jnhuang
Thank you for your kind words and support for our work!
Our paper is currently under review. Once this process is complete, we will
release the code.

Cheers,
Yeji

2024년 6월 27일 (목) 오후 5:12, jnhuang ***@***.***>님이 작성:

**Comment by Rbrq03** [comment]
@ldynx Thanks for your reply, I indeed think it's a valuable work, hope to see it soon !
